export { Login } from './Login'
export { LandingPage } from './LandingPage'
export { ProfessorsPage } from './ProfessorsPage'
export { ProfessorDetails } from './ProfessorDetails'
export { RatingPage } from './RatingPage'
export { UserProfile } from './UserProfile'
export { RegisterPage } from './RegisterPage'
export { AdminPanel } from './AdminPanel'