export { LandingTemplate } from "./LandingTemplate";
export { ProfessorTemplate } from './ProfessorTemplate';
export { ProfessorDetailsTemplate } from './ProfessorDetailsTemplate'
export { RatingTemplate } from './RatingTemplate'
export { AccountDetails } from './AccountDetails'
export { UserRatings } from './UserRatings'
export { SavedProfessors } from './SavedProfessors'
export { LoginTemplate } from './LoginTemplate'
export { RegisterTemplate } from './RegisterTemplate'
export { Professors } from './Professors'