export type { StatisticsType } from './StatisticsType'
export type { ProfessorType } from './ProfessorType'
export type { QuestionType } from './QuestionType'
export type { RatingChart } from './RatingChart'
export type { SchoolType } from './SchoolType'
export type { UserType } from './UserType'
export type { RateType } from './RateType'